# Schema for the theme setting configuration file of the EPIC theme.

epic_theme.settings:
  type: theme_settings
  label: 'EPIC Theme settings'
  mapping:
    cdn_provider:
      type: string
      label: 'CDN Provider'
    breadcrumb_home:
      type: integer
      label: 'Breadcrumb Home'
